services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      bash -c '
        bundle exec rails db:prepare &&
        bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}
      '
    volumes:
      - .:/rails
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOST: db
      PORT: ${PORT:-3000}

volumes:
  postgres_data:
